name: soracom-cli CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  soracom-cli:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          CLI_VERSION=$(curl -s https://api.github.com/repos/soracom/soracom-cli/releases/latest | jq -r .tag_name)
          BINARY_VERSION=$(echo $CLI_VERSION | sed 's/v//')
          curl -s -L -o soracom https://github.com/soracom/soracom-cli/releases/download/${CLI_VERSION}/soracom_${BINARY_VERSION}_linux_amd64
          chmod +x soracom
      - name: get sim list
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          AUTH_KEY_ID: ${{ secrets.AUTH_KEY_ID}}
        run: |
          ./soracom --coverage-type jp --auth-key-id $AUTH_KEY_ID --auth-key $AUTH_KEY sims list