name: soracom-cli CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  soracom-cli:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get sim list
        uses: ./
        with:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          AUTH_KEY_ID: ${{ secrets.AUTH_KEY_ID}}
